=== maksimrut/xmlTask/xmltask/src/main/resources/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/papers"
	xmlns:c="http://www.example.org/papers"
	elementFormDefault="qualified">

	<element name="papers">
		<complexType>
			<sequence>
				<element ref="tns:paperType" maxOccurs="unbounded" />
			</sequence>
		</complexType>	
	</element>

	<complexType name="paperType">
		<sequence>
			<element name="title" type="string" />
			<element name="language" type="tns:language" minOccurs="1" maxOccurs="unbounded" />
			<element name="date" type="gYearMonth" />
			<element name="colored" type="Boolean" />
			<element name="price" type="tns:price" />
		</sequence>
		<attribute name="id" type="tns:paperId" use="required" />
		<attribute name="website" type="string" use="optional" default="http://www.example.org" />
	</complexType>

	<complexType name="journalType">
		<complexContent>
			<extention base="tns:paperType">
				<sequence>
					<element name="points" type="unsignedInt" />
					<element name="scopus" type="Boolean" />
				</sequence>
			</extention>
		</complexContent>
	</complexType>

	<complexType name="catalogueType">
		<complexContent>
			<extention base="tns:paperType">
				<sequence>
					<element name="volume" type="unsignedInt" />
				</sequence>
			</extention>
		</complexContent>
	</complexType>

	<simpleType name="paperId">
		<restriction base="ID">
			<pattern value="\d{1,10}" />
		</restriction>
	</simpleType>

	<simpleType name="price">
		<restriction base="unsignedInt">
			<minInclusive value="0" />
			<maxInclusive value="1000" />
		</restriction>
	</simpleType>

	<simpleType name="language">
		<restriction base="string">
			<enumeration value="Russian" />
			<enumeration value="Belarusian" />
			<enumeration value="English" />
			<enumeration value="Polish" />
			<enumeration value="Hebrew" />
		</restriction>
	</simpleType>
	
	<element name="paper" type="tns:paperType" abstract="true" />
	
	<element name="journal" type="tns:journalType" substitutionGroup="tns:paper" />

	<element name="catalogue" type="tns:catalogueType" substitutionGroup="tns:paper" />
</schema>

=== maksimrut/xmlTask/xmltask/src/test/resources/papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/papers"
	xsi:schemaLocation="http://www.example.org/papers papers.xsd">

	<journal id="p2">
		<title>Technika</title>
		<language>Polish</language>
		<date>2005-03</date>
		<colored>false</colored>
		<price>5</price>
		<points>120</points>
		<scopus>true</scopus>
	</journal>

	<catalogue id="p3" website="qwe.rty">
		<title>Technika</title>
		<language>Polish</language>
		<date>2005-03</date>
		<colored>false</colored>
		<price>0</price>
		<volume>150</volume>
	</catalogue>

	<journal website="qwe.rty" id="p5">
		<title>Technika</title>
		<language>Russian</language>
		<date>2005-03</date>
		<colored>false</colored>
		<price>5</price>
		<points>20</points>
		<scopus>true</scopus>
	</journal>

	<catalogue id="p6">
		<title>VsiaTechnika</title>
		<language>Russian</language>
		<date>2005-03</date>
		<colored>false</colored>
		<price>0</price>
		<volume>180</volume>
	</catalogue>

	<journal id="p8">
		<title>Technika</title>
		<language>Belarusian</language>
		<date>2005-05</date>
		<colored>false</colored>
		<price>5</price>
		<points>120</points>
		<scopus>true</scopus>
	</journal>

	<catalogue id="p9">
		<title>NashaTechnika</title>
		<language>Belarusian</language>
		<date>2005-05</date>
		<colored>false</colored>
		<price>0</price>
		<volume>170</volume>
	</catalogue>

	<journal id="p11">
		<title>Bereshit</title>
		<language>Hebrew</language>
		<date>2005-07</date>
		<colored>true</colored>
		<price>5</price>
		<points>180</points>
		<scopus>true</scopus>
	</journal>

	<catalogue id="p12">
		<title>Alef</title>
		<language>English</language>
		<date>2005-07</date>
		<colored>false</colored>
		<price>0</price>
		<volume>150</volume>
	</catalogue>

	<journal id="p14">
		<title>Energy</title>
		<language>English</language>
		<date>2005-09</date>
		<colored>true</colored>
		<price>8</price>
		<points>120</points>
		<scopus>true</scopus>
	</journal>

	<journal id="p15">
		<title>Renewables</title>
		<language>English</language>
		<date>2005-09</date>
		<colored>true</colored>
		<price>7</price>
		<points>150</points>
		<scopus>false</scopus>
	</journal>

	<catalogue id="p16">
		<title>Technics</title>
		<language>English</language>
		<date>2005-09</date>
		<colored>false</colored>
		<price>0</price>
		<volume>150</volume>
	</catalogue>

	<journal id="p13" website="developers.com">
		<title>Developers</title>
		<language>English</language>
		<date>2010-09</date>
		<colored>true</colored>
		<price>10</price>
		<points>100</points>
		<scopus>true</scopus>
	</journal>

	<catalogue id="p10">
		<title>Tegilim</title>
		<language>Hebrew</language>
		<date>2015-10</date>
		<colored>false</colored>
		<price>10</price>
		<volume>200</volume>
	</catalogue>

	<journal id="p7">
		<title>Article</title>
		<language>Polish</language>
		<date>2007-09</date>
		<colored>false</colored>
		<price>7</price>
		<points>0</points>
		<scopus>false</scopus>
	</journal>

	<catalogue id="p4">
		<title>Tech</title>
		<language>English</language>
		<date>2020-09</date>
		<colored>false</colored>
		<price>20</price>
		<volume>400</volume>
	</catalogue>

	<journal id="p1">
		<title>Uperad</title>
		<language>Belarusian</language>
		<date>2020-09</date>
		<colored>true</colored>
		<price>7</price>
		<points>200</points>
		<scopus>true</scopus>
	</journal>
</papers>
